name: Build

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - run: go build -ldflags="-s -w" -v -o paimonmoe-link-${{github.ref_name}}.exe .

      - name: Run UPX
        uses: crazy-max/ghaction-upx@v2
        with:
          version: latest
          files: |
            paimonmoe-link-${{github.ref_name}}.exe
          args: --best

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: paimonmoe-link-${{github.ref_name}}.exe
